-- Idempotent production schema for AI Reliability Studio.
-- Raw secrets are intentionally absent from every table.

CREATE TABLE IF NOT EXISTS schema_migrations (
    version INTEGER PRIMARY KEY,
    applied_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT NOT NULL UNIQUE,
    display_name TEXT,
    auth_subject TEXT NOT NULL UNIQUE,
    disabled_at TIMESTAMPTZ,
    session_not_before TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS workspaces (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    retention_days INTEGER NOT NULL DEFAULT 90 CHECK (retention_days >= 0),
    pii_redaction_enabled BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS memberships (
    user_id BIGINT NOT NULL REFERENCES users(id),
    workspace_id BIGINT NOT NULL REFERENCES workspaces(id),
    role TEXT NOT NULL CHECK (role IN ('owner','admin','editor','reviewer','viewer')),
    revoked_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (user_id, workspace_id)
);
CREATE TABLE IF NOT EXISTS projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id BIGINT NOT NULL REFERENCES workspaces(id),
    name TEXT NOT NULL,
    use_case TEXT,
    industry TEXT,
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id BIGINT NOT NULL REFERENCES workspaces(id),
    project_id BIGINT REFERENCES projects(id),
    filename TEXT NOT NULL,
    safe_filename TEXT NOT NULL,
    content_hash TEXT,
    uploaded_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    chunk_count INTEGER NOT NULL DEFAULT 0,
    status TEXT NOT NULL DEFAULT 'indexed'
);
CREATE TABLE IF NOT EXISTS document_versions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id BIGINT NOT NULL REFERENCES workspaces(id),
    document_id BIGINT NOT NULL REFERENCES documents(id),
    version INTEGER NOT NULL,
    content_hash TEXT NOT NULL,
    extraction_warnings JSONB NOT NULL DEFAULT '[]'::jsonb,
    text_preview TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (document_id, version), UNIQUE (document_id, content_hash)
);
CREATE TABLE IF NOT EXISTS chunks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id BIGINT NOT NULL REFERENCES workspaces(id),
    document_id BIGINT NOT NULL REFERENCES documents(id),
    document_version_id BIGINT NOT NULL REFERENCES document_versions(id),
    source_name TEXT NOT NULL,
    filename TEXT NOT NULL,
    chunk_text TEXT NOT NULL,
    chunk_index INTEGER NOT NULL,
    chunk_id TEXT NOT NULL,
    page INTEGER,
    section TEXT,
    text_start INTEGER,
    text_end INTEGER,
    content_hash TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS prompts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id BIGINT NOT NULL REFERENCES workspaces(id),
    project_id BIGINT REFERENCES projects(id),
    prompt_name TEXT NOT NULL,
    prompt_text TEXT NOT NULL,
    prompt_type TEXT NOT NULL,
    current_version_id BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS prompt_versions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id BIGINT NOT NULL REFERENCES workspaces(id),
    prompt_id BIGINT NOT NULL REFERENCES prompts(id),
    version INTEGER NOT NULL,
    content TEXT NOT NULL,
    content_hash TEXT NOT NULL,
    change_explanation TEXT,
    motivated_by_failures JSONB NOT NULL DEFAULT '[]'::jsonb,
    created_by BIGINT REFERENCES users(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    promoted_at TIMESTAMPTZ,
    UNIQUE (prompt_id, version), UNIQUE (prompt_id, content_hash)
);
ALTER TABLE prompts DROP CONSTRAINT IF EXISTS prompts_current_version_id_fkey;
ALTER TABLE prompts ADD CONSTRAINT prompts_current_version_id_fkey FOREIGN KEY (current_version_id) REFERENCES prompt_versions(id);
CREATE TABLE IF NOT EXISTS datasets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id BIGINT NOT NULL REFERENCES workspaces(id),
    project_id BIGINT REFERENCES projects(id),
    name TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (workspace_id, project_id, name)
);
CREATE TABLE IF NOT EXISTS dataset_versions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id BIGINT NOT NULL REFERENCES workspaces(id),
    dataset_id BIGINT NOT NULL REFERENCES datasets(id),
    version INTEGER NOT NULL,
    content_hash TEXT NOT NULL,
    schema_version TEXT NOT NULL,
    rows_json JSONB NOT NULL,
    case_count INTEGER NOT NULL,
    immutable BOOLEAN NOT NULL DEFAULT false,
    created_by BIGINT REFERENCES users(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (dataset_id, version), UNIQUE (dataset_id, content_hash)
);
CREATE TABLE IF NOT EXISTS targets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id BIGINT NOT NULL REFERENCES workspaces(id),
    project_id BIGINT REFERENCES projects(id),
    name TEXT NOT NULL,
    target_type TEXT NOT NULL CHECK (target_type IN ('synthetic_mock','foundation_model','external_api')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (workspace_id, project_id, name)
);
CREATE TABLE IF NOT EXISTS target_versions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id BIGINT NOT NULL REFERENCES workspaces(id),
    target_id BIGINT NOT NULL REFERENCES targets(id),
    version INTEGER NOT NULL,
    version_hash TEXT NOT NULL,
    configuration_json JSONB NOT NULL,
    created_by BIGINT REFERENCES users(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (target_id, version), UNIQUE (target_id, version_hash)
);
CREATE TABLE IF NOT EXISTS eval_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id BIGINT NOT NULL REFERENCES workspaces(id),
    project_id BIGINT REFERENCES projects(id),
    run_name TEXT NOT NULL,
    timestamp TIMESTAMPTZ NOT NULL DEFAULT now(),
    model_name TEXT NOT NULL,
    mode TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending',
    target_type TEXT NOT NULL,
    target_version TEXT,
    dataset_version_id BIGINT REFERENCES dataset_versions(id),
    unique_case_count INTEGER NOT NULL,
    total_executions INTEGER NOT NULL,
    completed_executions INTEGER NOT NULL DEFAULT 0,
    cancel_requested BOOLEAN NOT NULL DEFAULT false,
    evaluator_version TEXT,
    label_semantics_version TEXT,
    threshold_version TEXT,
    calibration_status TEXT NOT NULL DEFAULT 'insufficiently_calibrated',
    calibration_version TEXT,
    manifest_json JSONB NOT NULL,
    notes TEXT
);
CREATE TABLE IF NOT EXISTS executions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id BIGINT NOT NULL REFERENCES workspaces(id),
    run_id BIGINT NOT NULL REFERENCES eval_runs(id),
    case_id TEXT NOT NULL,
    execution_key TEXT NOT NULL,
    prompt_version_id BIGINT REFERENCES prompt_versions(id),
    target_version_id BIGINT REFERENCES target_versions(id),
    status TEXT NOT NULL CHECK (status IN ('pending','running','passed','failed','timed_out','rate_limited','cancelled','invalid_response')),
    attempt_count INTEGER NOT NULL DEFAULT 0,
    started_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    latency_ms DOUBLE PRECISION,
    http_status INTEGER,
    provider TEXT,
    model TEXT,
    input_tokens INTEGER,
    output_tokens INTEGER,
    cost NUMERIC(18,8),
    error_code TEXT,
    safe_error TEXT,
    response_json JSONB,
    metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    UNIQUE (workspace_id, execution_key)
);
CREATE TABLE IF NOT EXISTS scores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id BIGINT NOT NULL REFERENCES workspaces(id),
    execution_id BIGINT NOT NULL REFERENCES executions(id),
    evaluator_version TEXT NOT NULL,
    determination_state TEXT NOT NULL,
    confidence DOUBLE PRECISION,
    metrics_json JSONB NOT NULL,
    explanation_json JSONB NOT NULL,
    failure_labels JSONB NOT NULL DEFAULT '[]'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS eval_results (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id BIGINT NOT NULL REFERENCES workspaces(id),
    run_id BIGINT NOT NULL REFERENCES eval_runs(id),
    evaluator_version TEXT,
    label_semantics_version TEXT,
    threshold_version TEXT,
    calibration_status TEXT NOT NULL DEFAULT 'insufficiently_calibrated',
    calibration_version TEXT,
    failure_reason_codes JSONB NOT NULL DEFAULT '[]'::jsonb,
    failure_evidence JSONB NOT NULL DEFAULT '{}'::jsonb,
    synthetic_prompt_ignored BOOLEAN NOT NULL DEFAULT false,
    result_json JSONB NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS judgments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id BIGINT NOT NULL REFERENCES workspaces(id),
    execution_id BIGINT NOT NULL REFERENCES executions(id),
    evaluator_type TEXT NOT NULL,
    provider TEXT,
    model TEXT,
    prompt TEXT,
    prompt_hash TEXT,
    temperature DOUBLE PRECISION,
    output_json JSONB NOT NULL,
    confidence DOUBLE PRECISION,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id BIGINT NOT NULL REFERENCES workspaces(id),
    execution_id BIGINT NOT NULL REFERENCES executions(id),
    author_id BIGINT NOT NULL REFERENCES users(id),
    parent_id BIGINT REFERENCES comments(id),
    body TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'open',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    resolved_at TIMESTAMPTZ
);
CREATE TABLE IF NOT EXISTS review_assignments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id BIGINT NOT NULL REFERENCES workspaces(id),
    execution_id BIGINT NOT NULL REFERENCES executions(id),
    reviewer_id BIGINT REFERENCES users(id),
    reason TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'needs_review',
    human_score DOUBLE PRECISION,
    automated_disagreement BOOLEAN NOT NULL DEFAULT false,
    decision TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    resolved_at TIMESTAMPTZ
);
CREATE TABLE IF NOT EXISTS calibration_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id BIGINT NOT NULL REFERENCES workspaces(id),
    dataset_version_id BIGINT REFERENCES dataset_versions(id),
    evaluator_version TEXT NOT NULL,
    threshold_version TEXT NOT NULL,
    calibration_version TEXT NOT NULL,
    status TEXT NOT NULL,
    reviewed_case_count INTEGER NOT NULL,
    result_json JSONB NOT NULL,
    created_by BIGINT NOT NULL REFERENCES users(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (workspace_id, calibration_version)
);
CREATE TABLE IF NOT EXISTS calibration_reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id BIGINT NOT NULL REFERENCES workspaces(id),
    calibration_run_id BIGINT REFERENCES calibration_runs(id),
    case_id TEXT NOT NULL,
    reviewer_id BIGINT NOT NULL REFERENCES users(id),
    human_labels JSONB NOT NULL,
    automatic_labels JSONB NOT NULL,
    split TEXT NOT NULL,
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (workspace_id, case_id, reviewer_id)
);
CREATE TABLE IF NOT EXISTS exports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id BIGINT NOT NULL REFERENCES workspaces(id),
    user_id BIGINT NOT NULL REFERENCES users(id),
    run_id BIGINT REFERENCES eval_runs(id),
    format TEXT NOT NULL,
    content_hash TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id BIGINT NOT NULL REFERENCES workspaces(id),
    user_id BIGINT NOT NULL REFERENCES users(id),
    action TEXT NOT NULL,
    entity_type TEXT NOT NULL,
    entity_id TEXT,
    metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS execution_cache (
    workspace_id BIGINT NOT NULL REFERENCES workspaces(id),
    cache_key TEXT NOT NULL,
    response_json JSONB NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    expires_at TIMESTAMPTZ,
    PRIMARY KEY (workspace_id, cache_key)
);
CREATE TABLE IF NOT EXISTS scheduled_evaluations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id BIGINT NOT NULL REFERENCES workspaces(id),
    project_id BIGINT NOT NULL REFERENCES projects(id),
    schedule TEXT NOT NULL,
    configuration_json JSONB NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT false,
    created_by BIGINT NOT NULL REFERENCES users(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_projects_workspace ON projects(workspace_id);
CREATE INDEX IF NOT EXISTS idx_chunks_workspace_document ON chunks(workspace_id, document_id);
CREATE INDEX IF NOT EXISTS idx_runs_workspace_timestamp ON eval_runs(workspace_id, timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_executions_workspace_run ON executions(workspace_id, run_id);
CREATE INDEX IF NOT EXISTS idx_scores_workspace_execution ON scores(workspace_id, execution_id);
CREATE INDEX IF NOT EXISTS idx_calibration_workspace_created ON calibration_runs(workspace_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_calibration_reviews_workspace_case ON calibration_reviews(workspace_id, case_id);

ALTER TABLE eval_runs ADD COLUMN IF NOT EXISTS evaluator_version TEXT;
ALTER TABLE eval_runs ADD COLUMN IF NOT EXISTS label_semantics_version TEXT;
ALTER TABLE eval_runs ADD COLUMN IF NOT EXISTS threshold_version TEXT;
ALTER TABLE eval_runs ADD COLUMN IF NOT EXISTS calibration_status TEXT NOT NULL DEFAULT 'insufficiently_calibrated';
ALTER TABLE eval_runs ADD COLUMN IF NOT EXISTS calibration_version TEXT;
ALTER TABLE eval_results ADD COLUMN IF NOT EXISTS evaluator_version TEXT;
ALTER TABLE eval_results ADD COLUMN IF NOT EXISTS label_semantics_version TEXT;
ALTER TABLE eval_results ADD COLUMN IF NOT EXISTS threshold_version TEXT;
ALTER TABLE eval_results ADD COLUMN IF NOT EXISTS calibration_status TEXT NOT NULL DEFAULT 'insufficiently_calibrated';
ALTER TABLE eval_results ADD COLUMN IF NOT EXISTS calibration_version TEXT;
ALTER TABLE eval_results ADD COLUMN IF NOT EXISTS failure_reason_codes JSONB NOT NULL DEFAULT '[]'::jsonb;
ALTER TABLE eval_results ADD COLUMN IF NOT EXISTS failure_evidence JSONB NOT NULL DEFAULT '{}'::jsonb;
ALTER TABLE eval_results ADD COLUMN IF NOT EXISTS synthetic_prompt_ignored BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE eval_results ADD COLUMN IF NOT EXISTS candidate_id TEXT;
ALTER TABLE eval_results ADD COLUMN IF NOT EXISTS candidate_name TEXT;
ALTER TABLE eval_results ADD COLUMN IF NOT EXISTS target_name TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS disabled_at TIMESTAMPTZ;
ALTER TABLE users ADD COLUMN IF NOT EXISTS session_not_before TIMESTAMPTZ;
ALTER TABLE memberships ADD COLUMN IF NOT EXISTS revoked_at TIMESTAMPTZ;

-- Application connections set `ars.user_id` and `ars.workspace_id` after auth.
-- RLS is defense in depth; repository queries remain explicitly workspace-scoped.
DO $$
DECLARE table_name TEXT;
BEGIN
    FOREACH table_name IN ARRAY ARRAY[
        'projects','documents','document_versions','chunks','prompts','prompt_versions',
        'datasets','dataset_versions','targets','target_versions','eval_runs','executions',
        'scores','eval_results','judgments','comments','review_assignments','calibration_runs',
        'calibration_reviews','exports','audit_logs',
        'execution_cache','scheduled_evaluations'
    ] LOOP
        EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', table_name);
        IF NOT EXISTS (
            SELECT 1 FROM pg_policies WHERE schemaname = current_schema()
              AND tablename = table_name AND policyname = 'workspace_isolation'
        ) THEN
            EXECUTE format(
                'CREATE POLICY workspace_isolation ON %I USING (workspace_id = current_setting(''ars.workspace_id'', true)::bigint) WITH CHECK (workspace_id = current_setting(''ars.workspace_id'', true)::bigint)',
                table_name
            );
        END IF;
    END LOOP;
    ALTER TABLE memberships ENABLE ROW LEVEL SECURITY;
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies WHERE schemaname = current_schema()
          AND tablename = 'memberships' AND policyname = 'membership_isolation'
    ) THEN
        CREATE POLICY membership_isolation ON memberships
          USING (
            user_id = NULLIF(current_setting('ars.user_id', true), '')::bigint
            OR workspace_id = NULLIF(current_setting('ars.workspace_id', true), '')::bigint
          )
          WITH CHECK (workspace_id = NULLIF(current_setting('ars.workspace_id', true), '')::bigint);
    END IF;
END $$;

INSERT INTO schema_migrations(version) VALUES (1) ON CONFLICT (version) DO NOTHING;
INSERT INTO schema_migrations(version) VALUES (7) ON CONFLICT (version) DO NOTHING;
